os: windows
language: shell
env:
  global:
  - PY37PATH=/c/Python39:/c/Python39/Scripts
matrix:
  include:
  - name: Build
    env: PATH=$PY37PATH:$PATH
    before_install:
    - choco install python
install:
- py -m pip install --upgrade pip
- py -m pip install -r requirements.txt
script:
- pyinstaller --noconfirm --onefile --name "fmi" main.py
- pyinstaller --noconfirm --onefile registerProtocol.py
- pyinstaller --noconfirm --onefile removeProtocol.py
