matrix:
  include:
    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
before_install:
  - python -m pip install -r requirements-test.txt
install:
  - python -m pip install -r requirements.txt
script:
  - python -m pyinstaller --noconfirm --onefile --name "fmi" main.py
  - python -m pyinstaller --noconfirm --onefile registerProtocol.py
  - python -m pyinstaller --noconfirm --onefile removeProtocol.py
deploy:
  provider: releases
  api_key: "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"
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
