os: windows
language: shell
env:
  global:
  - PY37PATH=/c/Python39:/c/Python39/Scripts
matrix:
  include:
  - name: Build
    env: PATH=$PY37PATH:$PATH
    before_install:
    - choco install python
install:
- py -m pip install --upgrade pip
- py -m pip install -r requirements.txt
script:
- pyinstaller --noconfirm --onefile --name "fmi" main.py
- pyinstaller --noconfirm --onefile registerProtocol.py
- pyinstaller --noconfirm --onefile removeProtocol.py
deploy:
  provider: releases
  api_key:
    secure: kXI56gclbCnB50RJVry3HVsRBMNtAbFt8X6at280dWc5HKq60GBHPy6Fnb0HuAgYDNWnUgCc5ZdAcyAr/W25rpjgY9MT9xMEI2SZ7IEiftIWBsLeLRh+hehlCt1IUDpu8tEuqBQXsPWPMsi9N7220+Rvz1JBapBLHXefuwcZJn25i5n/v3tw11zzllmV3pKClmbfNEPgGgijyEoVj6YjJz3xErb+hObTE/inXLODW26C9tBaHmBMAF+LV9ZQIeh4PuhYPtEHiIznVcRN2XK7gpoo0lggV6Pa7lt/abFij++MK9nv1XJu6H5xIOI073MLZ2r4Cw1SNib4PKUTx8YFMnyC8LiBVeez9lNa5hJDYWNsBWF/kT6dXEtqswCpy4STPOO+zmMBEVllfE60iNHiz65QdXZhgi7OGHa32VCKKjEKyRYVPEdXqCqLaRlStkHcnPGcAS2OX337IqaM5PbGA5ZJX5cbCeZ85a0aUk2MMxXRyX+j7yBBOrt6lf3ElrTfgUSbKCaH6CdN4++Dfe9Ne7Emv1Uy5hvSAJY9xx/cwfLHl+coH42vVY6cTjlW5LgmpRy+cGV+9CgW02Pu/wpUmCUto4NIqepKmAiWBwksj/0VfsfR7HIxzSyL/GngavH3bfcZ+uCRZuVESFv5+MXVgNdKhOwdbDGP3IJLeB+GAUA=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    branch: main
